import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';

const roboto = Roboto({
  weight: '500',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Find Plane Head',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
        style={{
          backgroundImage: `url(/background.jpg)`,
        }}
      >
        <section className="min-h-screen flex flex-col">
          {/* <Header /> */}
          <main className="flex flex-1 flex-col justify-center items-center">
            {children}
          </main>
          {/* <Footer /> */}
        </section>
      </body>
    </html>
  );
}
